# Exploring Orthology AGR data for BioThings Studio Parser

In [31]:
import pandas as pd
import numpy as np
import os, csv
import gzip
from biothings.utils.dataload import dict_convert, dict_sweep


## Example Data

In [35]:
infile = os.path.join("c:\\Users\\19802\\Documents\\dev\scripps\\BioThings_SuLab\\data\\drugLabels.byGene.tsv")
assert os.path.exists(infile2)

In [42]:
example_data=pd.read_csv(infile2, sep="\t",squeeze=True,quoting=csv.QUOTE_NONE).to_dict(orient='records') 

View the first record of the `example_data`. 


In [43]:
example_data[0]

{'Gene ID': 'PA267',
 'Gene Symbol': 'ABCB1',
 'Label IDs': 'PA166123409;PA166159586',
 'Label Names': 'Annotation of EMA Label for aliskiren and ABCB1;Annotation of HCSC Label for aliskiren and ABCB1'}

In [37]:
# we'll remove space in keys to make queries easier. Also, lowercase is preferred
# for a BioThings API. We'll an helper function from BioThings SDK
process_key = lambda k: k.replace(" ","_").lower()

In [44]:
# Test Example Parse
for rec in example_data[:2]:
    label_ids = rec.pop("Label IDs").split(";")
    label_names = rec.pop("Label Names").split(";")
    assert len(label_ids) == len(label_names)
    labels = []
    for i,_ in enumerate(label_ids):
        #print(label_ids[i])
        labels.append({"id" : label_ids[i],
                        "name" : label_names[i]})
    _id = rec["Gene ID"]
    rec = dict_convert(rec,keyfn=process_key)
    doc = {"_id" : _id, "drug_labels" : labels}

print(doc)

{'_id': 'PA390', 'drug_labels': [{'id': 'PA166184427', 'name': 'Annotation of Swissmedic Label for ezetimibe / rosuvastatin and ABCG2, SLCO1B1'}, {'id': 'PA166184499', 'name': 'Annotation of Swissmedic Label for rosuvastatin and ABCG2, SLCO1B1'}]}


In [45]:
example_data[0]

{'Gene ID': 'PA267', 'Gene Symbol': 'ABCB1'}

---

## Ortholog AGR Data  



### Load input data   

Datasource: ```https://fms.alliancegenome.org/download/ORTHOLOGY-ALLIANCE_COMBINED.tsv.gz```     
  
  
*The first lines (0-14) are summary information and are disregarded when formatting the dataframe.*

In [49]:
ortho_infile = os.path.join("c:\\Users\\19802\\Documents\\dev\scripps\\BioThings_SuLab\\data\\ORTHOLOGY-ALLIANCE_COMBINED.tsv.gz")
assert os.path.exists(infile)

In [50]:
# open and print the summary key at top of file

# open and load tsv into dataframe
with gzip.open(ortho_infile, 'rb') as f_in:
    orthoAGR=pd.read_csv(f_in, header=15, sep="\\t", engine="python")
    for line in f_in.readlines()[:15]:
        print(line)
    print("\n")
data_ortho_agr=orthoAGR.to_dict(orient='records')

print("[INFO] completed loading data.")




[INFO] completed loading data.


### Explore Data

For each column in the dataframe `orthoAGR` list out the name and the unique value count. *If the count is low, list the values.* 

In [51]:
# view orthology data columns available
orthoAGR.columns.values

array(['Gene1ID', 'Gene1Symbol', 'Gene1SpeciesTaxonID',
       'Gene1SpeciesName', 'Gene2ID', 'Gene2Symbol',
       'Gene2SpeciesTaxonID', 'Gene2SpeciesName', 'Algorithms',
       'AlgorithmsMatch', 'OutOfAlgorithms', 'IsBestScore',
       'IsBestRevScore'], dtype=object)

In [11]:
# Count unique values found in columns, if under a certain threshold view the unique list of values
for col in orthoAGR.columns.values:
    list_len=len(orthoAGR[col].unique().tolist())
    print("column: %s length: %s"%(col, list_len))
    if list_len < 20:
        print("unique values: ", orthoAGR[col].unique().tolist())


column: Gene1ID length: 100430
column: Gene1Symbol length: 81990
column: Gene1SpeciesTaxonID length: 7
unique values:  ['NCBITaxon:6239', 'NCBITaxon:7955', 'NCBITaxon:10116', 'NCBITaxon:10090', 'NCBITaxon:9606', 'NCBITaxon:7227', 'NCBITaxon:559292']
column: Gene1SpeciesName length: 7
unique values:  ['Caenorhabditis elegans', 'Danio rerio', 'Rattus norvegicus', 'Mus musculus', 'Homo sapiens', 'Drosophila melanogaster', 'Saccharomyces cerevisiae']
column: Gene2ID length: 100430
column: Gene2Symbol length: 81990
column: Gene2SpeciesTaxonID length: 7
unique values:  ['NCBITaxon:559292', 'NCBITaxon:7227', 'NCBITaxon:7955', 'NCBITaxon:10116', 'NCBITaxon:9606', 'NCBITaxon:6239', 'NCBITaxon:10090']
column: Gene2SpeciesName length: 7
unique values:  ['Saccharomyces cerevisiae', 'Drosophila melanogaster', 'Danio rerio', 'Rattus norvegicus', 'Homo sapiens', 'Caenorhabditis elegans', 'Mus musculus']
column: Algorithms length: 2529
column: AlgorithmsMatch length: 11
unique values:  [9, 8, 7, 10, 6

In [52]:
orthoAGR.head()

Gene1ID Gene1Symbol Gene1SpeciesTaxonID  \
0         WB:WBGene00011502      vps-53      NCBITaxon:6239   
1  ZFIN:ZDB-GENE-041114-199       vps53      NCBITaxon:7955   
2               RGD:1311391       Vps53     NCBITaxon:10116   
3               MGI:1915549       Vps53     NCBITaxon:10090   
4                HGNC:25608       VPS53      NCBITaxon:9606   

         Gene1SpeciesName         Gene2ID Gene2Symbol Gene2SpeciesTaxonID  \
0  Caenorhabditis elegans  SGD:S000003566       VPS53    NCBITaxon:559292   
1             Danio rerio  SGD:S000003566       VPS53    NCBITaxon:559292   
2       Rattus norvegicus  SGD:S000003566       VPS53    NCBITaxon:559292   
3            Mus musculus  SGD:S000003566       VPS53    NCBITaxon:559292   
4            Homo sapiens  SGD:S000003566       VPS53    NCBITaxon:559292   

           Gene2SpeciesName  \
0  Saccharomyces cerevisiae   
1  Saccharomyces cerevisiae   
2  Saccharomyces cerevisiae   
3  Saccharomyces cerevisiae   
4  Saccharomyces cerevisiae   

                                          Algorithms  AlgorithmsMatch  \
0  PhylomeDB|OrthoFinder|Hieranoid|OMA|Ensembl Co...                9   
1  OrthoFinder|Hieranoid|OMA|Ensembl Compara|Roun...                8   
2  OrthoFinder|Hieranoid|OMA|Ensembl Compara|InPa...                7   
3  PhylomeDB|OrthoFinder|Hieranoid|OMA|Ensembl Co...                9   
4  PhylomeDB|OrthoFinder|Hieranoid|OMA|Ensembl Co...                9   

   OutOfAlgorithms IsBestScore IsBestRevScore  
0               10         Yes            Yes  
1               10         Yes            Yes  
2                9         Yes            Yes  
3               10         Yes            Yes  
4               10         Yes            Yes

View the first record of the orthology AGR data, in `data_ortho_agr` list.

In [77]:
# view first record
data_ortho_agr[0]

{'Gene1ID': 'WB:WBGene00011502',
 'Gene1Symbol': 'vps-53',
 'Gene1SpeciesTaxonID': 'NCBITaxon:6239',
 'Gene1SpeciesName': 'Caenorhabditis elegans',
 'Gene2ID': 'SGD:S000003566',
 'Gene2Symbol': 'VPS53',
 'Gene2SpeciesTaxonID': 'NCBITaxon:559292',
 'Gene2SpeciesName': 'Saccharomyces cerevisiae',
 'Algorithms': 'PhylomeDB|OrthoFinder|Hieranoid|OMA|Ensembl Compara|Roundup|InParanoid|PANTHER|OrthoInspector',
 'AlgorithmsMatch': 9,
 'OutOfAlgorithms': 10,
 'IsBestScore': 'Yes',
 'IsBestRevScore': 'Yes'}

In [72]:
# Lets view a chunk of IDs to see the formatting
orthoAGR['Gene1ID'][:10]

0            WB:WBGene00011502
1     ZFIN:ZDB-GENE-041114-199
2                  RGD:1311391
3                  MGI:1915549
4                   HGNC:25608
5               FB:FBgn0031598
6    ZFIN:ZDB-GENE-070112-1002
7                  RGD:1586427
8                  MGI:2444430
9                   HGNC:19743
Name: Gene1ID, dtype: object

In [73]:
orthoAGR['Gene2ID'][:10]

0    SGD:S000003566
1    SGD:S000003566
2    SGD:S000003566
3    SGD:S000003566
4    SGD:S000003566
5    SGD:S000003566
6    SGD:S000000021
7    SGD:S000000021
8    SGD:S000000021
9    SGD:S000000021
Name: Gene2ID, dtype: object

### Parse Data
Now that we have loaded the data and correctly formatted it into records, we can loop through the new dictionary and access our data.

In [98]:

# Build Parser 
def load_orthology(data, data_list):
    results = {}

    for rec in data_ortho_agr[:4]:
        orig_id1= rec["Gene1ID"].split(':')
        id1_tag2=orig_id1[1]
        _id = id1_tag2
        rec = dict_convert(rec,keyfn=process_key)
        # remove NaN values, not indexable
        rec = dict_sweep(rec,vals=[np.nan])
        results.setdefault(_id,[]).append(rec)
        #print(rec)
    for _id,docs in results.items():
        doc = {"_id": _id, "orthology_data" : docs}
        yield doc
    
    #return results;

In [99]:
def load_testcase():
    results=load_orthology(orthoAGR, data_ortho_agr)
    #print(results)
    print(next(results))
load_testcase()

{'_id': 'WBGene00011502', 'orthology_data': [{'gene1id': 'WB:WBGene00011502', 'gene1symbol': 'vps-53', 'gene1speciestaxonid': 'NCBITaxon:6239', 'gene1speciesname': 'Caenorhabditis elegans', 'gene2id': 'SGD:S000003566', 'gene2symbol': 'VPS53', 'gene2speciestaxonid': 'NCBITaxon:559292', 'gene2speciesname': 'Saccharomyces cerevisiae', 'algorithms': 'PhylomeDB|OrthoFinder|Hieranoid|OMA|Ensembl Compara|Roundup|InParanoid|PANTHER|OrthoInspector', 'algorithmsmatch': 9, 'outofalgorithms': 10, 'isbestscore': 'Yes', 'isbestrevscore': 'Yes'}]}


```{'gene1id': 'WB:WBGene00011502', 'gene1symbol': 'vps-53', 'gene1speciestaxonid': 'NCBITaxon:6239', 'gene1speciesname': 'Caenorhabditis elegans', 'gene2id': 'SGD:S000003566', 'gene2symbol': 'VPS53', 'gene2speciestaxonid': 'NCBITaxon:559292', 'gene2speciesname': 'Saccharomyces cerevisiae', 'algorithms': 'PhylomeDB|OrthoFinder|Hieranoid|OMA|Ensembl Compara|Roundup|InParanoid|PANTHER|OrthoInspector', 'algorithmsmatch': 9, 'outofalgorithms': 10, 'isbestscore': 'Yes', 'isbestrevscore': 'Yes'}```


### Testing

In [54]:
!curl localhost:8000/metadata 

{"biothing_type": "gene", "build_date": "2021-09-14T15:46:03.681934", "build_version": "20210914", "src": {"orthologyAGR": {"stats": {"orthologyAGR": 100430}, "version": "2021-08"}}, "stats": {"total": 100430}}

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0


100   210  100   210    0     0    210      0  0:00:01 --:--:--  0:00:01  4468


In [66]:
!curl localhost:8000/query?q=orthology_data.gene1id:WB

{"took": 3, "total": 0, "max_score": null, "hits": []}


  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100    54  100    54    0     0     54      0  0:00:01 --:--:--  0:00:01  1148


In [101]:
curl -X GET localhost:9200/orthology/_search

SyntaxError: invalid syntax (<ipython-input-101-309fc1b91021>, line 1)

---

## Successful API Build Test Cases Result:  

```  
C:\Users\19802>curl localhost:8000/metadata
{"biothing_type": "gene", "build_date": "2021-09-13T19:03:47.233936", "build_version": "20210913", "src": {"orthologyAGR": {"stats": {"orthologyAGR": 100430}, "version": "2021-08"}}, "stats": {"total": 100430}}```

---